import styles from './page.module.css'
import Gallery from '../components/Gallery'
import Details from '../components/Details'
import Summary from '../components/Summary'
import Actions from '../components/Actions'
import Item01 from '../components/Item01'
import Item02 from '../components/Item02'
import Item03 from '../components/Item03'
import Item04 from '../components/Item04'
import Item05 from '../components/Item05'
import Item06 from '../components/Item06'
import Item07 from '../components/Item07'
import Item08 from '../components/Item08'
import Item09 from '../components/Item09'
import Item10 from '../components/Item10'
import Item11 from '../components/Item11'
import Item12 from '../components/Item12'
import Item13 from '../components/Item13'
import Item14 from '../components/Item14'
import Item15 from '../components/Item15'
import Item16 from '../components/Item16'
import Item17 from '../components/Item17'
import Item18 from '../components/Item18'
import Item19 from '../components/Item19'
import Item20 from '../components/Item20'

export default function Page() {
  return <main className={styles.main}><Gallery /><Details /><Summary /><Actions /><Item01 /><Item02 /><Item03 /><Item04 /><Item05 /><Item06 /><Item07 /><Item08 /><Item09 /><Item10 /><Item11 /><Item12 /><Item13 /><Item14 /><Item15 /><Item16 /><Item17 /><Item18 /><Item19 /><Item20 /></main>
}
