export async function getStaticPaths() {
  return {
    paths: [],
    fallback: false,
  }
}

export async function getStaticProps() {
  return {
    props: {
      data: "generated by getStaticProps",
    },
  }
}

export default function CmsPage({ data }) {
  if (data === undefined) {
    return <main id="unexpected-render">BUG: dynamic page rendered without static props</main>
  }

  return <main id="generated-page">{data}</main>
}
